### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jshin313** [ejmastnak/dotfiles#1]
Is it good if I just attribute with something like this and then copy & paste into my own snippets file?

```
# Taken from https://github.com/ejmastnak/dotfiles/blob/main/vim/UltiSnips/tex/math.snippets
snippet "([\W_])wt" "\widetilde" rA
`!p snip.rv = match.group(1)`\widetilde{${1:${VISUAL:}}}$0
endsnippet
```

Or do you want a full MIT license or BSD thing?

Thanks

**Comment by ejmastnak** [comment]
Thanks for asking. What you suggest is great, i.e. a link to the original file as a comment. No need in my opinion to go through a formal licensing process here, dotfiles are meant to be copied.
