### ISSUE TITLE
SELECT_RAW is now called LS_SELECT_RAW

### ISSUE THREAD

**Issue by albertfgu** [ejmastnak/dotfiles#3]
Thanks for the wonderful guide :) I enjoyed reading it and it helped me set up a modern Neovim config

I was fighting a bit with the snippet logic and found that the name of the `SELECT_RAW` variable seems to have been changed. It doesn't seem well documented so I'm not even sure how you found this solution at all... but at any rate changing the name in https://github.com/ejmastnak/dotfiles/blob/main/config/nvim/lua/personal/luasnip-helper-funcs.lua makes my setup work now.

**Comment by ejmastnak** [comment]
> Thanks for the wonderful guide :) I enjoyed reading it and it helped me set up a modern Neovim config

Thanks for letting me know, glad it was helpful :)

> I was fighting a bit with the snippet logic and found that the name of the SELECT_RAW variable seems to have been changed.

Thank you for pointing this out, much appreciated! Not sure how you found it but glad you did---I now see that the switch to the `LS_` env variable namespace is mentioned as a breaking change here: https://github.com/L3MON4D3/LuaSnip/issues/81#issuecomment-1235595467 

I'll update the guide online right now.

**Comment by ejmastnak** [comment]
Done! I've changed `SELECT_RAW` to `LS_SELECT_RAW` and added a short deprecation warning about the switch to the `LS_` prefix in https://github.com/ejmastnak/ejmastnak.com/commit/4d8cb673ccf688c0f5c8814b820d647e008f5d60

I've also taken the liberty of thanking you on the series homepage https://www.ejmastnak.com/tutorials/vim-latex/intro/#feedback; I hope that's alright with you!
